# A tool used by developers to identify spelling errors in text.
# Readers may ignore this file.

default_stages: [commit]

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell
        description: Check for spelling errors in text.
        entry: codespell
        language: python
        args:
          - "-L ocassion,occassion,ot,te,tje"
        files: \.txt$|\.md$|\.py|\.ipynb$
