name: Code tests (Windows)

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'    # Run workflow for changes in Python files
      - '**/*.ipynb'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pytest nbval
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test Selected Python Scripts
        shell: bash
        run: |
          pytest setup/02_installing-python-libraries/tests.py
          pytest ch04/01_main-chapter-code/tests.py
          pytest ch05/01_main-chapter-code/tests.py
          pytest ch06/01_main-chapter-code/tests.py

      - name: Validate Selected Jupyter Notebooks
        shell: bash
        run: |
          pytest --nbval ch02/01_main-chapter-code/dataloader.ipynb
          pytest --nbval ch03/01_main-chapter-code/multihead-attention.ipynb
          pytest --nbval ch02/04_bonus_dataloader-intuition/dataloader-intuition.ipynb
